spring:
  h2:
    console:
      enabled: true
      path: /coupon

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./coupon
    username: sa
    password:

    ## Hibernate
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true